CREATE DATABASE CUYURAYA;

USE CUYURAYA;

create table TBL_ROL (
	ID_ROL			        INT AUTO_INCREMENT PRIMARY KEY,
	NOMBRE			        VARCHAR(20) UNIQUE NOT NULL,
  ESTADO              VARCHAR(20) NOT NULL,
	FEC_CREACION		    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FEC_ACTUALIZACION 	TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

create table TBL_USUARIO (
	ID_USUARIO			    INT AUTO_INCREMENT PRIMARY KEY,
	NOMBRES				      VARCHAR(255) NOT NULL,
	PATERNO				      VARCHAR(255) NOT NULL,
	MATERNO				      VARCHAR(255) NOT NULL,
	DNI					        VARCHAR(8) UNIQUE NOT NULL,
	DIRECCION			      VARCHAR(255) NOT NULL,
	NUM_CONTRATO		    VARCHAR(255),
	TELEFONO			      VARCHAR(20),
	CLAVE				        VARCHAR(255) NOT NULL,
	ID_ROL				      INT NOT NULL,
  NUM_INTENTOS        INT NOT NULL DEFAULT 5,
  ESTADO              VARCHAR(20) NOT NULL,
	FEC_CREACION		    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FEC_ACTUALIZACION 	TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

alter table TBL_USUARIO add constraint FK1_USUARIO foreign key (ID_ROL) REFERENCES TBL_ROL (ID_ROL);

create table TBL_RUBRO (
	ID_RUBRO		        INT AUTO_INCREMENT PRIMARY KEY,
	TIPO_RUBRO		      VARCHAR(50) UNIQUE NOT NULL,
  ESTADO              VARCHAR(20) NOT NULL,
	FEC_CREACION		    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FEC_ACTUALIZACION 	TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

create table TBL_TIPO_MOVIMIENTO (
	ID_TIPO_MOV		      INT AUTO_INCREMENT PRIMARY KEY,
	CONCEPTO		        VARCHAR(255) UNIQUE NOT NULL,
	ID_RUBRO		        INT NOT NULL,
  ESTADO              VARCHAR(20) NOT NULL,
	FEC_CREACION		    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FEC_ACTUALIZACION 	TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

alter table TBL_TIPO_MOVIMIENTO add constraint FK1_TIPO_MOVIMIENTO foreign key (ID_RUBRO) REFERENCES TBL_RUBRO (ID_RUBRO);

create table TBL_MEDIDOR (
	ID_MEDIDOR		      INT AUTO_INCREMENT PRIMARY KEY,
	COD_MEDIDOR		      VARCHAR(255) UNIQUE NOT NULL,
	ID_USUARIO		      INT NULL,
  ESTADO              VARCHAR(20) NOT NULL,
	FEC_CREACION		    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FEC_ACTUALIZACION 	TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

alter table TBL_MEDIDOR add constraint FK1_MEDIDOR foreign key (ID_USUARIO) REFERENCES TBL_USUARIO (ID_USUARIO);

create table TBL_TARIFA (
  ID_TARIFA           INT AUTO_INCREMENT PRIMARY KEY,
  COD_TARIFA          VARCHAR(20) UNIQUE NOT NULL,
  DESCRIPCION         VARCHAR(50) NOT NULL,
  MONTO_TARIFA        DECIMAL NOT NULL,
  ESTADO              VARCHAR(20) NOT NULL,
	FEC_CREACION		    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FEC_ACTUALIZACION 	TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

create table TBL_LECTURA (
	ID_LECTURA			    INT AUTO_INCREMENT PRIMARY KEY,
	ID_MEDIDOR			    INT NOT NULL,
	LECTURA_ACTUAL		  BIGINT NOT NULL,
	LECTURA_ANTERIOR	  BIGINT,
	M3_CONSUMIDO		    DECIMAL NOT NULL,
	ID_TARIFA				    INT NOT NULL,
	MONTO_PAGAR			    DECIMAL NOT NULL,
  PORC_DESCUENTO      DECIMAL DEFAULT 0,
  MONTO_MULTA         DECIMAL DEFAULT 0,
	NUM_RECIBO          VARCHAR(20) UNIQUE NOT NULL,
	FECHA_LIMT_PAGO		  DATE NOT NULL,
	FECHA_CORTE			    DATE,
  COMENTARIO          VARCHAR(255),
  ESTADO              VARCHAR(20) NOT NULL,
	FEC_CREACION		    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FEC_ACTUALIZACION 	TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

alter table TBL_LECTURA add constraint FK1_LECTURA foreign key (ID_MEDIDOR) REFERENCES TBL_MEDIDOR (ID_MEDIDOR);

create table TBL_PAGO_RECIBO (
	ID_PAGO_RECIBO      INT AUTO_INCREMENT PRIMARY KEY,
	FECHA_PAGO			    DATE,
	MONTO_PAGO			    DECIMAL,
	ID_LECTURA			    INT NOT NULL,
	NUM_COMPROBANTE     VARCHAR(50),
  COMENTARIO          VARCHAR(255),
  ESTADO              VARCHAR(20) NOT NULL,
	FEC_CREACION		    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FEC_ACTUALIZACION 	TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

alter table TBL_PAGO_RECIBO add constraint FK1_PAGO_RECIBO foreign key (ID_LECTURA) REFERENCES TBL_LECTURA (ID_LECTURA);

create table TBL_CAJA (
	ID_CAJA				      INT AUTO_INCREMENT PRIMARY KEY,
	NUM_COMPROBANTE		  VARCHAR(50),
	ID_TIPO_MOV			    INT NOT NULL,
	FECHA_MOVIMIENTO	  DATE NOT NULL,
	DESCRIPCION			    VARCHAR(255),
	MONTO				        DECIMAL NOT NULL,
	ID_PAGO_RECIBO      INT,
  ESTADO              VARCHAR(20) NOT NULL,
	FEC_CREACION		    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FEC_ACTUALIZACION 	TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

alter table TBL_CAJA add constraint FK1_CAJA foreign key (ID_TIPO_MOV) REFERENCES TBL_TIPO_MOVIMIENTO (ID_TIPO_MOV);
alter table TBL_CAJA add constraint FK2_CAJA foreign key (ID_PAGO_RECIBO) REFERENCES TBL_PAGO_RECIBO (ID_PAGO_RECIBO);

INSERT TBL_ROL (NOMBRE, ESTADO) VALUES ('administrador', 'activo');
INSERT TBL_ROL (NOMBRE, ESTADO) VALUES ('operador', 'activo');
INSERT TBL_ROL (NOMBRE, ESTADO) VALUES ('invitado', 'activo');

INSERT TBL_TARIFA (COD_TARIFA, DESCRIPCION, MONTO_TARIFA, ESTADO) VALUES ('BASE', 'Tarifa base', 5.0, 'ACTIVO');

insert into TBL_RUBRO (TIPO_RUBRO, ESTADO) values ('Ingreso', 'ACTIVO');
insert into TBL_RUBRO (TIPO_RUBRO, ESTADO) values ('Egreso', 'ACTIVO');

insert into TBL_TIPO_MOVIMIENTO (CONCEPTO, ID_RUBRO, ESTADO) values ('Pago de Mora', 1, 'ACTIVO');
insert into TBL_TIPO_MOVIMIENTO (CONCEPTO, ID_RUBRO, ESTADO) values ('Otros Ingreso', 1, 'ACTIVO');
insert into TBL_TIPO_MOVIMIENTO (CONCEPTO, ID_RUBRO, ESTADO) values ('Instalaciones Nuevas', 1, 'ACTIVO');
insert into TBL_TIPO_MOVIMIENTO (CONCEPTO, ID_RUBRO, ESTADO) values ('Operador del Sistema', 2, 'ACTIVO');
insert into TBL_TIPO_MOVIMIENTO (CONCEPTO, ID_RUBRO, ESTADO) values ('Herramientas', 2, 'ACTIVO');
insert into TBL_TIPO_MOVIMIENTO (CONCEPTO, ID_RUBRO, ESTADO) values ('Viaticos y Pasajes', 2, 'ACTIVO');
insert into TBL_TIPO_MOVIMIENTO (CONCEPTO, ID_RUBRO, ESTADO) values ('Combustibles y lubricantes', 2, 'ACTIVO');

